vendor/rails:
  :type: git
  :repository: git://github.com/rails/rails.git
  :revision: v2.3.2.1
vendor/plugins/calendar_date_select:
  :type: git
  :repository: git://github.com/timcharper/calendar_date_select.git
  :revision: 88b7caf7acecf31186661c0efd6bc606cdcc666d
vendor/plugins/haml:
  :type: git
  :repository: git://github.com/nex3/haml.git
  :revision: 2.0.9
vendor/plugins/project_search:
  :type: git
  :repository: git://github.com/37signals/project_search.git
  :revision: 5d243711fbbd69ac08ba86418316bd15cffa0642
vendor/plugins/safe_mass_assignment:
  :type: git
  :repository: git://github.com/jamis/safe_mass_assignment.git
  :revision: 7d7e24e551254e0651f5cfb93d876beaed9ed7f7
vendor/plugins/globalize2:
  :type: git
  :repository: git://github.com/joshmh/globalize2.git
  :revision: 0.1.0_PR1
